### ISSUE TITLE
Unable to skip certificate check for HTTPS

### ISSUE THREAD

**Issue by simonpilota** [Callidus2000/ARAH#4]
There's no way to pass -SkipCertificateCheck to invoke-webrequest so my self signed HTTPS server (FortiManager) can't be queried.

**Comment by Callidus2000** [comment]
Hi,
thanks for the report, never was a problem for me as every cert is created by (at least) our company ca.

I'll add the feature to ARAH and to [my FortiManager Module](https://github.com/Callidus2000/FortiManager) asap and report afterwards.

**Comment by Callidus2000** [comment]
And welcome to GitHub 😄

**Comment by Callidus2000** [comment]
Implemented in the develop branch of ARAH and FortiManager. This way you can test if it's working:
```Powershell
git clone -b develop https://github.com/Callidus2000/ARAH.git
git clone -b develop https://github.com/Callidus2000/FortiManager.git
ipmo -Force .\ARAH\ARAH\ARAH.psd1
ipmo -Force .\FortiManager\FortigateManager\FortigateManager.psd1
$connection = Connect-FM -Credential $fortiCred -Url MyLocalServer -Adom $adom -SkipCheck CertificateCheck
```
The SkipCheck Parameter allows to Skip `CertificateCheck, HttpErrorCheck, HeaderValidation`.

**Comment by simonpilota** [comment]
Worked perfectly thanks using commands above and I recommend merging into main branch. Thanks for the ipmo instructions - I'm using the gits as submodules but was stuggling to get it to run the modules without installing via powershell gallery.

**Comment by Callidus2000** [comment]
> Worked perfectly thanks using commands above and I recommend merging into main branch. 

Merging was the plan after "it works" confirmation 😄 
First pull request #5  is currently running, after finish the new module version will be available in the gallery. Same for the fortimanager module afterwards, If no problems occur both new module versions should be available in the gallery today.

**Comment by Callidus2000** [comment]
Gallery is updated
